### PR TITLE
Add login endpoint

### PR DESCRIPTION
**Pull request by halfacat1**
Addresses #2 
Please let me know stylistic/linting standards I'm missing, as this is my first PR.

- Added `POST /api/login/` endpoint, along with the rest of the stack & tests
- Although the login body expects a `username`, the assumption is that's equivalent to `email`
- Judging from `UserController`, it's intended that we're able to load a user from its Repository by its `email`, as opposed to `id` (which is not known to consumer of the api). @nscharrenberg Is this consistent with your thinking?
- This may be goldplating, but I've added a `AUTH_TOKEN` placeholder in the response body, and I foresee something like that to be required for subsequent calls to other endpoints.

### CODE REVIEW

**Comment by NewLunarFire** [comment]
I don't know that we can assume that the username is an email. Ideally I would like people to be able to connect using social media accounts (Google, Twitter, Facebook, etc.) to prevent them from having to create yet another account on a new service. But for now it's good enough to do so, as I would like to move on to adding more useful features to the prototype.

**Comment by halfacat1** [comment]
@NewLunarFire Thanks for clafiying. I agree SSO will be nice down the road, but we'll focus on building a MVP first.

**Comment by nscharrenberg** [comment]
Agree, with eventually having some SSO implementation, but for the MVP this would be fine.

> Although the login body expects a `username`, the assumption is that's equivalent to `email`

Refactoring username to email might be better imo, as it gives more clarity to whoever joins up. Don't think it would be a huge task to refactor it (pycharm should be able to refactor all references, excl. body responses maybe).

> Repository by its email, as opposed to id (which is not known to consumer of the api). @nscharrenberg Is this consistent with your thinking?

That's fine, I only added some boilerplate code to it, so the structure is known. Searching be email instead of ID (as this might not be known by the API) would be fine imo.

> This may be goldplating, but I've added a AUTH_TOKEN placeholder in the response body, and I foresee something like that to be required for subsequent calls to other endpoints.

it's fine for the MVP implementation, imo.

**Comment by nscharrenberg** [comment]
Will check the code tonight

**Pull request merged**
